In [10]:
import cv2
import threading
import time
from deepface import DeepFace

# List of available models and distance metrics
models = ["VGG-Face", "Facenet", "Facenet512", "OpenFace", "DeepFace", "DeepID", "ArcFace", "Dlib", "SFace"]
metrics = ["cosine", "euclidean", "euclidean_l2"]

# Initialize RTSP URL for IP camera
rtsp_url = "rtsp://admin:namtiep2005@192.168.1.25:554/Streaming/channels/101"
cap = cv2.VideoCapture(rtsp_url)  # Connect to IP camera

frame = None
ret = False
stop_thread = False

# Function to read frames from the IP camera
def read_frames():
    global frame, ret, stop_thread
    while not stop_thread:
        ret, frame = cap.read()
        # if ret:
            # frame = cv2.resize(frame, (640, 480))

# Start a separate thread for reading the video frames
thread = threading.Thread(target=read_frames)
thread.start()

# Function for real-time face recognition
def realtime_face_recognition():
    global frame, ret, stop_thread
    prev_time = 0  # Variable to store the previous frame time

    while not stop_thread:
        if ret:
            # Get the current time to calculate FPS
            current_time = time.time()
            fps = 1 / (current_time - prev_time)  # FPS calculation
            prev_time = current_time

            # Get the dimensions of the frame
            frame_height, frame_width, _ = frame.shape
            frame_area = frame_width * frame_height

            # Perform face recognition on the captured frame
            try:
                people = DeepFace.find(img_path=frame, db_path="image_in/", model_name="ArcFace", distance_metric=metrics[2], detector_backend="opencv", align = True, enforce_detection=False)

                for person in people:
                    # Retrieve the coordinates of the face bounding box
                    x = person['source_x'][0]
                    y = person['source_y'][0]
                    w = person['source_w'][0]
                    h = person['source_h'][0]

                    # Calculate the bounding box area
                    bounding_box_area = w * h

                    # Only process if the bounding box area is <= 90% of the total frame area
                    if bounding_box_area <= 0.9 * frame_area:

                        # Draw a rectangle around the face
                        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)

                        # Get the person's name and display it on the image
                        name = person['identity'][0].split('/')[-1]
                        cv2.putText(frame, name, (x, y), cv2.FONT_ITALIC, 1, (0, 0, 255), 2)
            except Exception as e:
                print(f"Error during face recognition: {e}")

            # Display the model name on the frame
            cv2.putText(frame, "Model: Facenet512", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

            # Display FPS on the frame
            cv2.putText(frame, f"FPS: {int(fps)}", (10, 70), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

            frame = cv2.resize(frame, (1600, 900))
            # Display the resulting frame
            cv2.imshow('Face Recognition', frame)

        # Check if 'q' is pressed to quit the program
        if cv2.waitKey(1) & 0xFF == ord('q'):
            stop_thread = True
            break

    # Stop reading frames and release resources
    thread.join()
    cap.release()
    cv2.destroyAllWindows()

# Start real-time face recognition
realtime_face_recognition()

24-09-26 16:32:46 - Searching [[[54 61 60]
  [54 61 60]
  [54 61 60]
  ...
  [74 78 78]
  [74 78 78]
  [74 78 78]]

 [[54 61 60]
  [54 61 60]
  [54 61 60]
  ...
  [74 78 78]
  [74 78 78]
  [74 78 78]]

 [[54 61 60]
  [54 61 60]
  [54 61 60]
  ...
  [74 78 78]
  [74 78 78]
  [74 78 78]]

 ...

 [[46 63 61]
  [46 63 61]
  [46 63 61]
  ...
  [40 56 56]
  [43 59 59]
  [43 59 59]]

 [[52 62 61]
  [52 62 61]
  [52 62 61]
  ...
  [57 66 67]
  [60 69 70]
  [60 69 70]]

 [[52 62 61]
  [52 62 61]
  [52 62 61]
  ...
  [51 60 61]
  [48 57 58]
  [48 57 58]]] in 34 length datastore
24-09-26 16:32:47 - find function duration 1.02567720413208 seconds
24-09-26 16:32:47 - Searching [[[53 60 59]
  [53 60 59]
  [53 60 59]
  ...
  [75 79 79]
  [75 79 79]
  [75 79 79]]

 [[53 60 59]
  [53 60 59]
  [53 60 59]
  ...
  [75 79 79]
  [75 79 79]
  [75 79 79]]

 [[53 60 59]
  [53 60 59]
  [53 60 59]
  ...
  [75 79 79]
  [75 79 79]
  [75 79 79]]

 ...

 [[47 59 64]
  [47 59 64]
  [47 59 64]
  ...
  [44 57 59]
  [45

In [1]:
import torch

# Check if CUDA is available
if torch.cuda.is_available():
    print(f"CUDA is available. PyTorch is using GPU: {torch.cuda.get_device_name(0)}")
    print(f"Number of GPUs available: {torch.cuda.device_count()}")
    print(f"Current CUDA device: {torch.cuda.current_device()}")
else:
    print("CUDA is not available. PyTorch is using the CPU.")


CUDA is available. PyTorch is using GPU: Quadro T1000 with Max-Q Design
Number of GPUs available: 1
Current CUDA device: 0


In [ ]:
from facenet_pytorch import MTCNN, InceptionResnetV1

# If required, create a face detection pipeline using MTCNN:
mtcnn = MTCNN(image_size=<image_size>, margin=<margin>)

# Create an inception resnet (in eval mode):
resnet = InceptionResnetV1(pretrained='vggface2').eval()

In [7]:
import cv2
import threading
import time
import numpy as np
import insightface

# Load the InsightFace model with Core ML execution provider
detector = insightface.app.FaceAnalysis(providers=['CUDAExecutionProvider'])
detector.prepare(ctx_id=0)  # ctx_id=0 cho GPU, ctx_id=-1 cho CPU nếu cần

# Initialize RTSP URL for IP camera
rtsp_url = "rtsp://admin:namtiep2005@192.168.1.25:554/Streaming/channels/101"
cap = cv2.VideoCapture(rtsp_url)  # Connect to IP camera

frame = None
ret = False
stop_thread = False

# Function to read frames from the IP camera
def read_frames():
    global frame, ret, stop_thread
    while not stop_thread:
        ret, frame = cap.read()

# Start a separate thread for reading the video frames
thread = threading.Thread(target=read_frames)
thread.start()

# Function for real-time face recognition
def realtime_face_recognition():
    global frame, ret, stop_thread
    prev_time = 0  # Variable to store the previous frame time

    while not stop_thread:
        if ret:
            # Get the current time to calculate FPS
            current_time = time.time()
            fps = 1 / (current_time - prev_time)  # FPS calculation
            prev_time = current_time

            # Perform face detection
            faces = detector.get(frame)

            if faces is not None:
                for face in faces:
                    # Draw a rectangle around the face
                    bbox = face.bbox.astype(int)
                    x1, y1, x2, y2 = bbox
                    cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)

                    # Display the person's face ID
                    cv2.putText(frame, f"ID: {face.embedding}", (x1, y1-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 255), 2)

            # Display the model name and FPS on the frame
            cv2.putText(frame, "Model: ArcFace (CoreML)", (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
            cv2.putText(frame, f"FPS: {int(fps)}", (10, 70), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

            frame = cv2.resize(frame, (1600, 900))
            # Display the resulting frame
            cv2.imshow('Face Recognition', frame)

        # Check if 'q' is pressed to quit the program
        if cv2.waitKey(1) & 0xFF == ord('q'):
            stop_thread = True
            break

    # Stop reading frames and release resources
    thread.join()
    cap.release()
    cv2.destroyAllWindows()

# Start real-time face recognition

realtime_face_recognition()

2024-09-26 16:31:16.283684150 [E:onnxruntime:Default, provider_bridge_ort.cc:1992 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1637 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.9: cannot open shared object file: No such file or directory

2024-09-26 16:31:16.789284054 [E:onnxruntime:Default, provider_bridge_ort.cc:1992 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1637 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.9: cannot open shared object file: No such file or directory



Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/dat/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/dat/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0


2024-09-26 16:31:16.816834513 [E:onnxruntime:Default, provider_bridge_ort.cc:1992 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1637 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.9: cannot open shared object file: No such file or directory

2024-09-26 16:31:16.847138362 [E:onnxruntime:Default, provider_bridge_ort.cc:1992 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1637 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.9: cannot open shared object file: No such file or directory



Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/dat/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/dat/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}


2024-09-26 16:31:16.958716657 [E:onnxruntime:Default, provider_bridge_ort.cc:1992 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1637 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.9: cannot open shared object file: No such file or directory



find model: /home/dat/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
